### ISSUE TITLE
idont know whet this is the problem

### ISSUE THREAD

**Issue by jamel-boussaada** [fastapi/full-stack-fastapi-template#368]
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\python\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "c:\python\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\python\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\python\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\python\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\python\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\python\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "c:\python\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\python\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\python\lib\site-packages\fastapi\routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "c:\python\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "c:\python\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "c:\python\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".\main2.py", line 31, in db_test
    mycursor.execute("SELECT * FROM student")
  File "c:\python\lib\site-packages\mysql\connector\cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "c:\python\lib\site-packages\mysql\connector\connection.py", line 686, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "c:\python\lib\site-packages\mysql\connector\connection.py", line 573, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'test.student' doesn't exist

**Comment by NMisko** [comment]
Hi,
did you run a migration?

Read this section here: https://github.com/tiangolo/full-stack-fastapi-postgresql/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D#migrations

**Comment by YuriiMotov** [comment]
Hope it was solved)
