### ISSUE TITLE
ERROR: Service 'frontend' failed to build, when executing `docker-compose up -d`

### ISSUE THREAD

**Issue by joao-parana** [fastapi/full-stack-fastapi-template#505]
Error when executing `docker-compose up -d`

```text
. . .

Step 9/13 : RUN npm run build
 ---> Running in d7c0f6e642bd

> frontend@0.1.0 build /app
> vue-cli-service build


-  Building for production...
 ERROR  Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at api.chainWebpack.config (/app/node_modules/@vue/cli-plugin-typescript/index.js:106:16)
    at webpackChainFns.forEach.fn (/app/node_modules/@vue/cli-service/lib/Service.js:236:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/app/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at PluginAPI.resolveChainableWebpackConfig (/app/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/app/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/app/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at api.registerCommand (/app/node_modules/@vue/cli-service/lib/commands/build/index.js:89:13)
    at Service.run (/app/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/app/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-27T23_02_59_539Z-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by david-shiko** [comment]
The same

**Comment by kamilgrymuza** [comment]
Setting the following versions in `frontend/package.json` solved it for me:
```
    "@vue/cli-plugin-typescript": "~4.1.0",
    "@vue/cli-plugin-unit-jest": "~4.1.0",
    ```
    
    but now I'm running into other frontend problems related to TypeScript compilation

**Comment by AlanMars** [comment]
> Error when executing `docker-compose up -d`
> 
> ```
> . . .
> 
> Step 9/13 : RUN npm run build
>  ---> Running in d7c0f6e642bd
> 
> > frontend@0.1.0 build /app
> > vue-cli-service build
> 
> 
> -  Building for production...
>  ERROR  Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
> Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at api.chainWebpack.config (/app/node_modules/@vue/cli-plugin-typescript/index.js:106:16)
>     at webpackChainFns.forEach.fn (/app/node_modules/@vue/cli-service/lib/Service.js:236:40)
>     at Array.forEach (<anonymous>)
>     at Service.resolveChainableWebpackConfig (/app/node_modules/@vue/cli-service/lib/Service.js:236:26)
>     at PluginAPI.resolveChainableWebpackConfig (/app/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
>     at module.exports (/app/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
>     at build (/app/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
>     at api.registerCommand (/app/node_modules/@vue/cli-service/lib/commands/build/index.js:89:13)
>     at Service.run (/app/node_modules/@vue/cli-service/lib/Service.js:230:12)
>     at Object.<anonymous> (/app/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! frontend@0.1.0 build: `vue-cli-service build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the frontend@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2023-03-27T23_02_59_539Z-debug.log
> ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
> ```

This issue has been addressed by #471 
here is the solution: https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/471

**Comment by YuriiMotov** [comment]
Outdated
