### ISSUE TITLE
NonTemplatedInputDirException

### ISSUE THREAD

**Issue by mh-mohaghegh75** [fastapi/full-stack-fastapi-template#556]
hi 
I'm trying to deploy this project but when i ran this command:

> $ pip install cookiecutter
> $ cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql

i have got this error:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/cookiecutter/cli.py", line 202, in main
    cookiecutter(
  File "/home/user/.local/lib/python3.11/site-packages/cookiecutter/main.py", line 184, in cookiecutter
    result = generate_files(
             ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/cookiecutter/generate.py", line 304, in generate_files
    template_dir = find_template(repo_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/cookiecutter/find.py", line 24, in find_template
    raise NonTemplatedInputDirException
cookiecutter.exceptions.NonTemplatedInputDirException
```

it seems template directory has been removed. but i would be appreciate if anyone answer my problem.
thanks.

**Comment by Kotwic4** [comment]
Same problem

**Comment by Kotwic4** [comment]
Cookiecutter was remove in this PR: https://github.com/tiangolo/full-stack-fastapi-postgresql/commit/455de4d9a95771931eba35aebacc6d8d282b38e7

**Comment by Kotwic4** [comment]
@tiangolo why did you remove cookiecutter? https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/553

**Comment by sdplatt** [comment]
too monolithic? Strip it down into pluggable components?

**Comment by enrique-zarate** [comment]
So, what's an alternative?

**Comment by sdplatt** [comment]
Alternative to being monolithic?

**Comment by enrique-zarate** [comment]
Sorry, I mean an alternative to running `cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql`. I want to start the project from scratch since it had a few changes since last week.

**Comment by Kotwic4** [comment]
I think @tiangolo instead of making master an usable, should instead have a branch with new version and merge to master when it is ready. The warning that the master is not updated until refactor in new version would good enough. The main problme is that this repo is pointed on [the official docs of fastapi](https://fastapi.tiangolo.com/project-generation/)

**Comment by asalyga** [comment]
@enrique-zarate Cookiecutter allows to run from [.zip files](https://cookiecutter.readthedocs.io/en/1.7.2/usage.html#works-with-zip-files), My way of handling it was to download the pre #553 merge version as zip file and just ran it with zip file, worked completely fine

**Comment by nazmi** [comment]
> how to create project now? readme not updated

Use this
```bash
cookie-cutter https://github.com/tiangolo/full-stack-fastapi-postgresql --checkout 30c722339b4fa6d4c2bd3deb7cca6fc3d9568f83
```

**Comment by nawideck** [comment]
Same problem

**Comment by webneshin** [comment]
Same problem

**Comment by YuriiMotov** [comment]
Outdated
